# Generated by roxytest: do not edit by hand!

# File R/constants.r: @tests

test_that("Function match_dist_name() @ L200", {
  expect_equal(match_dist_name("Weibull", survreg_dists, "survreg"), "weibull")
  expect_equal(match_dist_name("EXPONENTIAL", survreg_dists, "survreg"), "exponential")
  expect_error(
   match_dist_name("gamma", survreg_dists, "survreg"),
   'is not a supported distribution',
   fixed = TRUE
  )
})


test_that("Function check_source_params() @ L235", {
  expect_silent(
   check_source_params(
       list(intercept = 3, scale = 0.8),
       c("intercept", "scale"),
       "survreg",
       "weibull"
   )
  )
  expect_error(
   check_source_params(
       list(intercept = 3),
       c("intercept", "scale"),
       "survreg",
       "weibull"
   ),
   'required parameters missing',
   fixed = TRUE
  )
})


test_that("Function check_numeric_param() @ L265", {
  expect_silent(check_numeric_param(3.5, "intercept", "survreg", "weibull"))
  expect_error(
   check_numeric_param("a", "intercept", "survreg", "weibull"),
   'must be a single non-NA numeric value',
   fixed = TRUE
  )
  expect_error(
   check_numeric_param(NA, "intercept", "survreg", "weibull"),
   'must be a single non-NA numeric value',
   fixed = TRUE
  )
  expect_error(
   check_numeric_param(c(1, 2), "intercept", "survreg", "weibull"),
   'must be a single non-NA numeric value',
   fixed = TRUE
  )
})

