# Generated by roxytest: do not edit by hand!

# File R/apply_hr.r: @tests

test_that("Function apply_hr() @ L62", {
  dist1 <- define_surv_param("exp", rate = 0.25)
  expect_equal(
   apply_hr(dist1, 0.5),
   create_list_object(c('surv_ph', 'surv_dist'), dist = dist1, hr = 0.5)
  )
  expect_equal(
   apply_hr(dist1, 0.5),
   apply_hr(apply_hr(dist1, 0.5), 1)
  )
  expect_equal(
   apply_hr(dist1, 0.25),
   apply_hr(apply_hr(dist1, 0.5), 0.5)
  )
  expect_equal(
   apply_hr(dist1, 0.5),
   apply_hr(dist1, log(0.5), TRUE)
  )
  expect_error(
   apply_hr('foo', 0.5),
   'Error applying hazard ratio, invalid survival distribution provided.',
   fixed = TRUE
  )
  expect_error(
   apply_hr(dist1, 'foo'),
   'Error applying hazard ratio, "hr" must be numeric.',
   fixed = TRUE
  )
  expect_error(
   apply_hr(dist1, NA_real_),
   'Error applying hazard ratio, "hr" cannot be NA.',
   fixed = TRUE
  )
  expect_error(
   apply_hr(dist1, -2),
   'Error applying hazard ratio, "hr" cannot be negative.',
   fixed = TRUE
  )
})


test_that("Function surv_prob.surv_ph() @ L135", {
  dist1 <- define_surv_param("exp", rate = 0.50)
  dist2 <- define_surv_param("exp", rate = 0.25)
  dist3 <- apply_hr(dist1, 0.5)
  dist4 <- apply_hr(dist1, log(0.5), TRUE)
  expect_equal(
   surv_prob(dist2, seq_len(100)),
   surv_prob(dist3, seq_len(100))
  )
  expect_equal(
   surv_prob(dist2, seq_len(100)),
   surv_prob(dist4, seq_len(100))
  )
})


test_that("Function surv_quantile.surv_ph() @ L162", {
  dist1 <- define_surv_param('weibull', shape = 1.5, scale = 20)
  
  # PH algebra: Q_ph(p) = Q_inner(p^(1/hr))
  expect_equal(
   surv_quantile(apply_hr(dist1, 2), 0.5),
   surv_quantile(dist1, 0.5^(1/2)),
   tolerance = 1e-10
  )
  
  # Roundtrip
  ph_dist <- apply_hr(dist1, 0.7)
  probs <- c(0.9, 0.5, 0.1)
  times <- surv_quantile(ph_dist, probs)
  expect_equal(surv_prob(ph_dist, times), probs, tolerance = 1e-6)
  
  # hr=0 means survival never drops: Q(p<1) = Inf
  hr0_dist <- apply_hr(dist1, 0)
  expect_equal(surv_quantile(hr0_dist, 0.5), Inf)
  expect_equal(surv_quantile(hr0_dist, 1), 0)
})


test_that("Function print.surv_ph() @ L184", {
  dist1 <- apply_hr(define_surv_param('exp', rate = 0.025), 0.5)
  expect_output(
   print(dist1),
   'A proportional hazards survival distribution:
    * Hazard Ratio: 0.5
    * Baseline Distribution: An exponential distribution (rate = 0.025).',
   fixed = T
  )
})

