# Generated by roxytest: do not edit by hand!

# File R/openqalysurv.r: @tests

test_that("Function .onLoad() @ L35", {
  options(
   list(
       openqalysurv.show_call_signature_in_errors = NULL,
       openqalysurv.show_call_signature_in_warnings = NULL
   )
  )
  .onLoad()
  expect_equal(
   c(
       'openqalysurv.show_call_signature_in_errors',
       'openqalysurv.show_call_signature_in_warnings'
   ) %in% names(options()),
   c(TRUE, TRUE)
  )
})

