# Generated by roxytest: do not edit by hand!

# File R/surv_param_streg.r: @tests

test_that("Function define_surv_streg() @ L173", {
  # --- AFT metric ---
  
  # Exponential AFT
  dist1 <- define_surv_streg("exponential", cons = 3, metric = "aft")
  ref1 <- define_surv_param("exp", rate = exp(-3))
  expect_equal(class(dist1), c('surv_parametric', 'surv_dist'))
  expect_equal(
   surv_prob(dist1, c(0, 5, 10, 20)),
   surv_prob(ref1, c(0, 5, 10, 20))
  )
  
  # Weibull AFT
  dist2 <- define_surv_streg("weibull", cons = 3, ln_p = 0.405, metric = "aft")
  ref2 <- define_surv_param("weibull", shape = exp(0.405), scale = exp(3))
  expect_equal(
   surv_prob(dist2, c(0, 5, 10, 20)),
   surv_prob(ref2, c(0, 5, 10, 20))
  )
  
  # Lognormal AFT
  dist3 <- define_surv_streg("lognormal", cons = 2.5, sigma = 0.7, metric = "aft")
  ref3 <- define_surv_param("lnorm", meanlog = 2.5, sdlog = 0.7)
  expect_equal(
   surv_prob(dist3, c(0, 5, 10, 20)),
   surv_prob(ref3, c(0, 5, 10, 20))
  )
  
  # Log-logistic AFT
  dist4 <- define_surv_streg("loglogistic", cons = 3, gamma = 1.667, metric = "aft")
  ref4 <- define_surv_param("llogis", shape = 1.667, scale = exp(3))
  expect_equal(
   surv_prob(dist4, c(0, 5, 10, 20)),
   surv_prob(ref4, c(0, 5, 10, 20))
  )
  
  # Generalized gamma AFT
  dist5 <- define_surv_streg("ggamma", cons = 2.3, sigma = 0.4, kappa = -0.03, metric = "aft")
  ref5 <- define_surv_param("gengamma", mu = 2.3, sigma = 0.4, Q = -0.03)
  expect_equal(
   surv_prob(dist5, c(0, 5, 10, 20)),
   surv_prob(ref5, c(0, 5, 10, 20))
  )
  
  # --- PH metric ---
  
  # Exponential PH
  dist6 <- define_surv_streg("exponential", cons = -3, metric = "ph")
  ref6 <- define_surv_param("exp", rate = exp(-3))
  expect_equal(
   surv_prob(dist6, c(0, 5, 10, 20)),
   surv_prob(ref6, c(0, 5, 10, 20))
  )
  
  # Weibull PH
  dist7 <- define_surv_streg("weibull", cons = -2, ln_p = 0.405, metric = "ph")
  ref7 <- define_surv_param("weibullPH", shape = exp(0.405), scale = exp(-2))
  expect_equal(
   surv_prob(dist7, c(0, 5, 10, 20)),
   surv_prob(ref7, c(0, 5, 10, 20))
  )
  
  # Gompertz PH
  dist8 <- define_surv_streg("gompertz", cons = -3, gamma = 0.05, metric = "ph")
  ref8 <- define_surv_param("gompertz", shape = 0.05, rate = exp(-3))
  expect_equal(
   surv_prob(dist8, c(0, 5, 10, 20)),
   surv_prob(ref8, c(0, 5, 10, 20))
  )
  
  # Case insensitive
  dist9 <- define_surv_streg("Weibull", cons = 3, ln_p = 0.405, metric = "aft")
  expect_equal(
   surv_prob(dist9, c(0, 5, 10)),
   surv_prob(dist2, c(0, 5, 10))
  )
  
  # Invalid distribution for metric
  expect_error(
   define_surv_streg("gompertz", cons = 3, gamma = 0.05, metric = "aft"),
   'is not a supported distribution',
   fixed = TRUE
  )
  
  # Invalid distribution
  expect_error(
   define_surv_streg("gamma", cons = 3, metric = "aft"),
   'is not a supported distribution',
   fixed = TRUE
  )
  
  # Missing parameter
  expect_error(
   define_surv_streg("weibull", cons = 3, metric = "aft"),
   'required parameters missing',
   fixed = TRUE
  )
  
  # Invalid parameter value
  expect_error(
   define_surv_streg("weibull", cons = NA, ln_p = 0.5, metric = "aft"),
   'must be a single non-NA numeric value',
   fixed = TRUE
  )
})

