# Generated by roxytest: do not edit by hand!

# File R/surv_quantile.r: @tests

test_that("Function surv_quantile.default() @ L60", {
  dist1 <- define_surv_param('exp', rate = 0.05)
  
  # Roundtrip: surv_prob(dist, surv_quantile(dist, p)) ~ p
  probs <- c(0.9, 0.5, 0.1)
  times <- surv_quantile(dist1, probs)
  expect_equal(surv_prob(dist1, times), probs, tolerance = 1e-6)
  
  # Edge cases
  expect_equal(surv_quantile(dist1, 1), 0)
  expect_equal(surv_quantile(dist1, 0), Inf)
  
  # Validation
  expect_error(
   surv_quantile(dist1, 1.5),
   'Error computing survival quantiles, "probs" must be numeric values in the interval [0, 1].',
   fixed = TRUE
  )
  expect_error(
   surv_quantile(dist1, -0.1),
   'Error computing survival quantiles, "probs" must be numeric values in the interval [0, 1].',
   fixed = TRUE
  )
  expect_error(
   surv_quantile(dist1, NA_real_),
   'Error computing survival quantiles, "probs" cannot contain NA values.',
   fixed = TRUE
  )
  expect_error(
   surv_quantile(dist1, 'foo'),
   'Error computing survival quantiles, "probs" must be numeric values in the interval [0, 1].',
   fixed = TRUE
  )
})


test_that("Function check_probs() @ L78", {
  expect_silent(check_probs(c(0, 0.5, 1)))
  expect_error(check_probs(1.5), 'must be numeric values', fixed = TRUE)
  expect_error(check_probs(-0.1), 'must be numeric values', fixed = TRUE)
  expect_error(check_probs(NA_real_), 'cannot contain NA', fixed = TRUE)
  expect_error(check_probs('foo'), 'must be numeric values', fixed = TRUE)
})


test_that("Function find_search_upper() @ L93", {
  dist1 <- define_surv_param('exp', rate = 0.05)
  expect_true(is.finite(find_search_upper(dist1, 0.5)))
  expect_true(surv_prob(dist1, find_search_upper(dist1, 0.01)) < 0.01)
})

