# Generated by roxytest: do not edit by hand!

# File R/surv_param_survreg.r: @tests

test_that("Function define_surv_survreg() @ L108", {
  # Exponential
  dist1 <- define_surv_survreg("exponential", intercept = 3)
  ref1 <- define_surv_param("exp", rate = exp(-3))
  expect_equal(class(dist1), c('surv_parametric', 'surv_dist'))
  expect_equal(
   surv_prob(dist1, c(0, 5, 10, 20)),
   surv_prob(ref1, c(0, 5, 10, 20))
  )
  
  # Weibull
  dist2 <- define_surv_survreg("weibull", intercept = 3, scale = 0.8)
  ref2 <- define_surv_param("weibull", shape = 1/0.8, scale = exp(3))
  expect_equal(
   surv_prob(dist2, c(0, 5, 10, 20)),
   surv_prob(ref2, c(0, 5, 10, 20))
  )
  
  # Lognormal
  dist3 <- define_surv_survreg("lognormal", intercept = 2.5, scale = 0.7)
  ref3 <- define_surv_param("lnorm", meanlog = 2.5, sdlog = 0.7)
  expect_equal(
   surv_prob(dist3, c(0, 5, 10, 20)),
   surv_prob(ref3, c(0, 5, 10, 20))
  )
  
  # Log-logistic
  dist4 <- define_surv_survreg("loglogistic", intercept = 3, scale = 0.6)
  ref4 <- define_surv_param("llogis", shape = 1/0.6, scale = exp(3))
  expect_equal(
   surv_prob(dist4, c(0, 5, 10, 20)),
   surv_prob(ref4, c(0, 5, 10, 20))
  )
  
  # Case insensitive
  dist5 <- define_surv_survreg("Weibull", intercept = 3, scale = 0.8)
  expect_equal(
   surv_prob(dist5, c(0, 5, 10)),
   surv_prob(dist2, c(0, 5, 10))
  )
  
  # Invalid distribution
  expect_error(
   define_surv_survreg("gamma", intercept = 3),
   'is not a supported distribution',
   fixed = TRUE
  )
  
  # Invalid parameter value (NA)
  expect_error(
   define_surv_survreg("weibull", intercept = NA, scale = 0.8),
   'must be a single non-NA numeric value',
   fixed = TRUE
  )
  
  # Invalid parameter value (non-numeric)
  expect_error(
   define_surv_survreg("weibull", intercept = "a", scale = 0.8),
   'must be a single non-NA numeric value',
   fixed = TRUE
  )
})

