# Generated by roxytest: do not edit by hand!

# File R/max_hazards.r: @tests

test_that("Function max_hazards() @ L71", {
  dist1 <- define_surv_param("exp", rate = 0.01)
  dist2 <- define_surv_param("exp", rate = 0.02)
  dist3 <- define_surv_param("weibull", shape = 1.5, scale = 50)
  
  expect_equal(
   max_hazards(dist1, dist2),
   create_list_object(
       c('surv_max_haz', 'surv_combined', 'surv_dist'),
       dists = list(dist1, dist2),
       cycle_length = 1
   )
  )
  
  # Custom cycle_length
  expect_equal(
   max_hazards(dist1, dist2, cycle_length = 0.5)$cycle_length,
   0.5
  )
  
  # Three distributions
  expect_equal(
   length(max_hazards(dist1, dist2, dist3)$dists),
   3
  )
  
  # Error: invalid dist
  expect_error(
   max_hazards(dist1, 'foo'),
   'Error computing maximum hazards, invalid survival distribution provided.',
   fixed = TRUE
  )
  
  # Error: invalid cycle_length
  expect_error(
   max_hazards(dist1, dist2, cycle_length = -1),
   'Error computing maximum hazards, "cycle_length" must be a single positive numeric value.',
   fixed = TRUE
  )
  
  expect_error(
   max_hazards(dist1, dist2, cycle_length = 0),
   'Error computing maximum hazards, "cycle_length" must be a single positive numeric value.',
   fixed = TRUE
  )
})


test_that("Function surv_prob.surv_max_haz() @ L119", {
  # Two exponentials: max_hazards(exp(0.01), exp(0.02)) ~ exp(0.02)
  dist1 <- define_surv_param("exp", rate = 0.01)
  dist2 <- define_surv_param("exp", rate = 0.02)
  mh <- max_hazards(dist1, dist2)
  times <- seq(1, 50, by = 1)
  expect_equal(
   surv_prob(mh, times),
   surv_prob(dist2, times),
   tolerance = 1e-6
  )
  
  # S(0) = 1 and monotonically decreasing
  expect_equal(surv_prob(mh, 0), 1)
  s_vals <- surv_prob(mh, 0:100)
  expect_true(all(diff(s_vals) <= 0))
})


test_that("Function surv_quantile.surv_max_haz() @ L192", {
  dist1 <- define_surv_param("exp", rate = 0.01)
  dist2 <- define_surv_param("exp", rate = 0.02)
  mh <- max_hazards(dist1, dist2)
  
  # Roundtrip
  probs <- c(0.9, 0.5)
  times <- surv_quantile(mh, probs)
  expect_equal(surv_prob(mh, times), probs, tolerance = 0.01)
  
  # Edge cases
  expect_equal(surv_quantile(mh, 1), 0)
  expect_equal(surv_quantile(mh, 0), Inf)
})


test_that("Function print.surv_max_haz() @ L228", {
  dist1 <- define_surv_param("exp", rate = 0.01)
  dist2 <- define_surv_param("exp", rate = 0.02)
  expect_output(
   print(max_hazards(dist1, dist2)),
   'A survival distribution taking the maximum hazard of:',
   fixed = TRUE
  )
})

