# Generated by roxytest: do not edit by hand!

# File R/surv_km.r: @tests

c("test_that(\"Function define_surv_km() @ L81\", {\n  df <- data.frame(\n       month = c(0, 1, 5, 10),\n       p_surv = c(1, 0.9, 0.7, 0.5)\n  )\n  df2 <- data.frame(\n       month = c(0, 1, 5, 10),\n       p_surv = c('100%', '90%', '70%', '50%')\n  )\n  dist1 <- define_surv_km(df, 'month', 'p_surv')\n  dist2 <- define_surv_km(df[c(4,1,3,2), ], 'month', 'p_surv')\n  dist3 <- define_surv_km(mutate(df, time = month, survival = p_surv))\n  dist4 <- define_surv_km(df2, 'month', 'p_surv')\n  expect_equal(dist1, dist2)\n  expect_equal(dist1, dist3)\n  expect_equal(dist1, dist4)\n  \n  expect_error(\n   define_surv_km(data.frame()),\n   'Error defining KM, the following columns were expected but not found: \"time\", \"survival\".',\n    fixed = TRUE\n  )\n  expect_error(\n   define_surv_km(\n       mutate(df, p_surv = c(1, 0.9, 0.7, 0.9)), 'month', 'p_surv'\n   ),\n   'Error defining KM, column \"p_surv\" may not be increasing with respect to \"month\".',\n    fixed = TRUE\n  )\n  expect_error(\n   define_surv_km(\n       mutate(df, month = c(0, 1, 1, 10)), 'month', 'p_surv'\n   ),\n   'Error defining KM, column \"month\" contained duplicate values.',\n   fixed = TRUE\n  )\n  expect_error(\n   define_surv_km(df[-1, ], 'month', 'p_surv'),\n   fixed = TRUE,\n   'Error defining KM, column \"month\" must start with a value 0 and \"p_surv\" must start with a value 1.'\n  )\n  expect_error(\n   define_surv_km(mutate(df, p_surv = NA), 'month', 'p_surv'),\n   fixed = TRUE,\n   'Error defining KM, the following columns contained missing values: \"p_surv\".'\n  )\n  expect_error(\n   define_surv_km(mutate(df, p_surv = \"foo\"), 'month', 'p_surv'),\n   fixed = TRUE,\n   'Error defining KM, the following columns were of invalid type: \"p_surv\".'\n  )\n  expect_error(\n   define_surv_km(mutate(df, p_surv = 1.2), 'month', 'p_surv'),\n   fixed = TRUE,\n   'Error defining KM, values in column \"p_surv\" must be within the interval [0-1].'\n  )\n})\n", 
"test_that(\"Function define_surv_km() @ L81\", {\n  df <- data.frame(\n       time = c(0, 1, 5, 10),\n       survival = c(1, 0.9, 0.7, 0.5)\n  )\n  dist1 <- define_surv_table(df)\n  dist2 <- define_surv_km(df)\n  expect_equal(dist1, dist2)\n})\n")

test_that("Function print.surv_km() @ L194", {
  df <- data.frame(
       month = c(0, 1, 5, 10),
       p_surv = c(1, 0.9, 0.7, 0.5)
  )
  dist1 <- define_surv_km(df, 'month', 'p_surv')
  expect_output(
       print(dist1),
       "A Kaplan-Meier distribution:",
       fixed = T
  )
})


test_that("Function surv_prob.surv_km() @ L236", {
  df <- data.frame(
       time = c(0, 1, 5, 10),
       survival = c(1, 0.9, 0.7, 0.5)
  )
  dist1 <- define_surv_table(df)
  expect_equal(
   surv_prob(dist1, c(0, 0.99, 1, 1.01, 4.99, 5, 5.01, 11)),
   c(1, 1, 0.9, 0.9, 0.9, 0.7, 0.7, NA)
  )
  df2 <- data.frame(
       time = c(0, 1, 5, 10),
       survival = c(1, 0.9, 0.7, 0)
  )
  dist2 <- define_surv_table(df2)
  expect_equal(
   surv_prob(dist2, c(0, 0.99, 1, 1.01, 4.99, 5, 5.01, 11)),
   c(1, 1, 0.9, 0.9, 0.9, 0.7, 0.7, 0)
  )
})

