# Generated by roxytest: do not edit by hand!

# File R/apply_td_hr.r: @tests

test_that("Function apply_td_hr() @ L104", {
  dist1 <- define_surv_param("exp", rate = 0.1)
  
  # Delegation to apply_hr when length(hr) == 1
  expect_equal(
   apply_td_hr(dist1, 0, 0.5),
   apply_hr(dist1, 0.5)
  )
  
  # Log scale delegation
  expect_equal(
   apply_td_hr(dist1, 0, log(0.5), TRUE),
   apply_hr(dist1, 0.5)
  )
  
  # Basic structure for td_hr
  td_dist <- apply_td_hr(dist1, 0:1, c(0.5, 0.8))
  expect_true(inherits(td_dist, 'surv_td_ph'))
  expect_true(inherits(td_dist, 'surv_dist'))
  expect_equal(td_dist$hr, c(0.5, 0.8))
  expect_equal(td_dist$time, c(0, 1))
  
  # Duplicate (time, hr) pairs are deduplicated
  td_dup <- apply_td_hr(dist1, c(0, 1, 0, 1), c(0.5, 0.8, 0.5, 0.8))
  expect_equal(td_dup$time, c(0, 1))
  expect_equal(td_dup$hr, c(0.5, 0.8))
  
  # Error conditions
  expect_error(
   apply_td_hr('foo', 0:1, c(0.5, 0.8)),
   'Error applying time-dependent hazard ratio, invalid survival distribution provided.',
   fixed = TRUE
  )
  expect_error(
   apply_td_hr(dist1, 0:1, 'foo'),
   'Error applying time-dependent hazard ratio, "hr" must be numeric.',
   fixed = TRUE
  )
  expect_error(
   apply_td_hr(dist1, 0:1, c(0.5, NA_real_)),
   'Error applying time-dependent hazard ratio, "hr" cannot contain NA values.',
   fixed = TRUE
  )
  expect_error(
   apply_td_hr(dist1, 0:1, c(0.5, -0.2)),
   'Error applying time-dependent hazard ratio, "hr" cannot contain negative values.',
   fixed = TRUE
  )
  expect_error(
   apply_td_hr(dist1, c(0, 1, 2), c(0.5, 0.8)),
   'Error applying time-dependent hazard ratio, "time" and "hr" must have the same length.',
   fixed = TRUE
  )
  expect_error(
   apply_td_hr(dist1, c(0, 1, 0), c(0.5, 0.8, 0.7)),
   'Error applying time-dependent hazard ratio, conflicting hazard ratios found for the same time value.',
   fixed = TRUE
  )
})


test_that("Function surv_prob.surv_td_ph() @ L285", {
  dist1 <- define_surv_param("exp", rate = 0.1)
  
  # Constant HR should match apply_hr
  td_dist <- apply_td_hr(dist1, 0:99, rep(0.5, 100))
  ph_dist <- apply_hr(dist1, 0.5)
  expect_equal(
   surv_prob(td_dist, 0:99),
   surv_prob(ph_dist, 0:99),
   tolerance = 1e-10
  )
  
  # Identity: HR = 1 should match baseline
  td_dist_id <- apply_td_hr(dist1, 0:49, rep(1, 50))
  expect_equal(
   surv_prob(td_dist_id, 0:49),
   surv_prob(dist1, 0:49),
   tolerance = 1e-10
  )
  
  # Time = 0 should always be 1
  td_dist2 <- apply_td_hr(dist1, 0:2, c(0.5, 0.8, 1.2))
  expect_equal(surv_prob(td_dist2, 0), 1)
  
  # Error when time exceeds max stored time
  expect_error(
   surv_prob(td_dist2, 5),
   'Error calculating survival probabilities, query time exceeds maximum stored time.',
   fixed = TRUE
  )
  
  # CORE VALIDATION: td_hr should match join + apply_hr for piecewise constant HR
  # HR=0.5 for [0,2), HR=0.8 for [2,4)
  td_dist3 <- apply_td_hr(dist1, 0:3, c(0.5, 0.5, 0.8, 0.8))
  join_dist <- join(apply_hr(dist1, 0.5), 2, apply_hr(dist1, 0.8))
  test_times <- c(0, 0.5, 1, 1.5, 2, 2.5, 3)
  expect_equal(
   surv_prob(td_dist3, test_times),
   surv_prob(join_dist, test_times),
   tolerance = 1e-10
  )
  
  # Multiple HR transitions: HR=0.5 for [0,2), HR=1.0 for [2,4), HR=1.5 for [4,6)
  td_dist4 <- apply_td_hr(dist1, 0:5, c(0.5, 0.5, 1.0, 1.0, 1.5, 1.5))
  join_dist2 <- join(apply_hr(dist1, 0.5), 2, apply_hr(dist1, 1.0), 4, apply_hr(dist1, 1.5))
  test_times2 <- c(0, 1, 2, 3, 4, 5)
  expect_equal(
   surv_prob(td_dist4, test_times2),
   surv_prob(join_dist2, test_times2),
   tolerance = 1e-10
  )
  
  # Non-exponential: Weibull distribution
  dist_weib <- define_surv_param("weibull", shape = 1.5, scale = 10)
  td_weib <- apply_td_hr(dist_weib, 0:3, c(0.5, 0.5, 0.8, 0.8))
  join_weib <- join(apply_hr(dist_weib, 0.5), 2, apply_hr(dist_weib, 0.8))
  expect_equal(
   surv_prob(td_weib, test_times),
   surv_prob(join_weib, test_times),
   tolerance = 1e-10
  )
  
  # Composite baseline: apply_hr on top of existing surv_ph
  dist_ph <- apply_hr(dist1, 0.7)
  td_composite <- apply_td_hr(dist_ph, 0:3, c(0.5, 0.5, 0.8, 0.8))
  join_composite <- join(apply_hr(dist_ph, 0.5), 2, apply_hr(dist_ph, 0.8))
  expect_equal(
   surv_prob(td_composite, test_times),
   surv_prob(join_composite, test_times),
   tolerance = 1e-10
  )
  
  # NON-ALIGNED QUERY TIMES: query times between stored HR time points
  
  # Test: sparse stored times, queries fall between them
  td_sparse <- apply_td_hr(dist1, c(0, 2, 4), c(0.5, 0.8, 1.0))
  join_sparse <- join(apply_hr(dist1, 0.5), 2, apply_hr(dist1, 0.8), 4, apply_hr(dist1, 1.0))
  expect_equal(
   surv_prob(td_sparse, c(0, 1, 2, 3, 4)),
   surv_prob(join_sparse, c(0, 1, 2, 3, 4)),
   tolerance = 1e-10
  )
  
  # Test: fractional query times
  expect_equal(
   surv_prob(td_sparse, c(0, 0.5, 1.5, 2, 2.5, 3.5, 4)),
   surv_prob(join_sparse, c(0, 0.5, 1.5, 2, 2.5, 3.5, 4)),
   tolerance = 1e-10
  )
  
  # Test: sparse stored, dense queries
  td_dense <- apply_td_hr(dist1, c(0, 5, 10), c(0.5, 0.8, 1.0))
  join_dense <- join(apply_hr(dist1, 0.5), 5, apply_hr(dist1, 0.8), 10, apply_hr(dist1, 1.0))
  expect_equal(
   surv_prob(td_dense, seq(0, 10, by = 0.5)),
   surv_prob(join_dense, seq(0, 10, by = 0.5)),
   tolerance = 1e-10
  )
  
  # Test: Weibull with non-aligned times
  dist_weib2 <- define_surv_param("weibull", shape = 1.5, scale = 10)
  td_weib2 <- apply_td_hr(dist_weib2, c(0, 2, 5), c(0.5, 0.8, 1.2))
  join_weib2 <- join(apply_hr(dist_weib2, 0.5), 2, apply_hr(dist_weib2, 0.8), 5, apply_hr(dist_weib2, 1.2))
  expect_equal(
   surv_prob(td_weib2, c(0, 0.5, 1, 1.5, 2, 2.5, 3, 4, 5)),
   surv_prob(join_weib2, c(0, 0.5, 1, 1.5, 2, 2.5, 3, 4, 5)),
   tolerance = 1e-10
  )
  
  # Test: single query point mid-interval
  expect_equal(surv_prob(td_dense, 3), surv_prob(join_dense, 3), tolerance = 1e-10)
  expect_equal(surv_prob(td_dense, 7), surv_prob(join_dense, 7), tolerance = 1e-10)
})


test_that("Function print.surv_td_ph() @ L312", {
  dist1 <- apply_td_hr(define_surv_param('exp', rate = 0.1), 0:2, c(0.5, 0.8, 1.2))
  expect_output(print(dist1), 'time-dependent proportional hazards')
})

