# Generated by roxytest: do not edit by hand!

# File R/surv_random.r: @tests

test_that("Function surv_random() @ L52", {
  # Exponential: large sample mean ~ 1/rate
  set.seed(42)
  dist1 <- define_surv_param('exp', rate = 0.1)
  samples <- surv_random(dist1, 5000)
  expect_equal(mean(samples), 10, tolerance = 1)
  
  # Cure model: some samples are Inf
  set.seed(42)
  cure_dist <- define_surv_cure('exp', theta = 0.3, rate = 0.1, mixture = TRUE)
  cure_samples <- surv_random(cure_dist, 1000)
  prop_inf <- mean(is.infinite(cure_samples))
  expect_equal(prop_inf, 0.3, tolerance = 0.05)
  
  # Validation
  expect_error(
   surv_random(dist1, -1),
   'Error generating random survival times, "n" must be a single positive integer.',
   fixed = TRUE
  )
  expect_error(
   surv_random(dist1, 0),
   'Error generating random survival times, "n" must be a single positive integer.',
   fixed = TRUE
  )
  expect_error(
   surv_random(dist1, 'foo'),
   'Error generating random survival times, "n" must be a single positive integer.',
   fixed = TRUE
  )
})


test_that("Function check_n() @ L64", {
  expect_silent(check_n(10))
  expect_error(check_n(-1), 'must be a single positive integer', fixed = TRUE)
  expect_error(check_n(0), 'must be a single positive integer', fixed = TRUE)
  expect_error(check_n('foo'), 'must be a single positive integer', fixed = TRUE)
  expect_error(check_n(c(1, 2)), 'must be a single positive integer', fixed = TRUE)
})

