# Generated by roxytest: do not edit by hand!

# File R/surv_param_flexsurv.r: @tests

test_that("Function define_surv_flexsurv() @ L84", {
  dist1 <- define_surv_flexsurv(distribution = "exp", rate = 0.05)
  expect_equal(class(dist1), c('surv_parametric', 'surv_dist'))
  expect_equal(dist1$distribution, 'exp')
  expect_equal(dist1$parameters, list(rate = 0.05))
  
  expect_error(
   define_surv_flexsurv(distribution = "weibull", shape = 1.2),
   'Error defining Weibull (AFT) distribution, parameters missing from function call: "scale".',
   fixed = TRUE
  )
  
  dist2 <- define_surv_flexsurv("weibull", shape = 1.5, scale = 20)
  ref2 <- define_surv_param("weibull", shape = 1.5, scale = 20)
  expect_equal(
   surv_prob(dist2, c(0, 5, 10, 20)),
   surv_prob(ref2, c(0, 5, 10, 20))
  )
})

