// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_td_surv_prob
NumericVector compute_td_surv_prob(NumericVector query_time, NumericVector stored_time, NumericVector hr, NumericVector log_surv_stored, NumericVector log_surv_query);
RcppExport SEXP _openqalysurv_compute_td_surv_prob(SEXP query_timeSEXP, SEXP stored_timeSEXP, SEXP hrSEXP, SEXP log_surv_storedSEXP, SEXP log_surv_querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type query_time(query_timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stored_time(stored_timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hr(hrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_surv_stored(log_surv_storedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_surv_query(log_surv_querySEXP);
    rcpp_result_gen = Rcpp::wrap(compute_td_surv_prob(query_time, stored_time, hr, log_surv_stored, log_surv_query));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_openqalysurv_compute_td_surv_prob", (DL_FUNC) &_openqalysurv_compute_td_surv_prob, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_openqalysurv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
