# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_td_surv_prob <- function(query_time, stored_time, hr, log_surv_stored, log_surv_query) {
    .Call(`_openqalysurv_compute_td_surv_prob`, query_time, stored_time, hr, log_surv_stored, log_surv_query)
}

